import { ref } from 'vue'

export type UiLanguage = 'en' | 'zh-CN'

const UI_LANGUAGE_STORAGE_KEY = 'codex-web-local.ui-language.v1'

const zhCN: Record<string, string> = {
  'English': 'English',
  'Simplified Chinese': '简体中文',
  'Commands': '命令',
  'Local': '本地',
  'Compact the current thread context': '压缩当前线程上下文',
  'Open the code review pane': '打开代码审查面板',
  'Rename the current thread': '重命名当前线程',
  'Archive the current thread': '归档当前线程',
  'Fork the current thread': '派生当前线程',
  'Start a new thread': '新建线程',
  'Open the skills page': '打开技能页面',
  'Generate or update AGENTS.md': '生成或更新 AGENTS.md',
  'Show help about Codex': '显示 Codex 使用帮助',
  'Mention files with @': '使用 @ 提及文件',
  'Show the current git diff': '显示当前 git diff',
  'Clear the input': '清空输入',
  'Search threads': '搜索线程',
  'Filter threads...': '筛选线程...',
  'Clear search': '清除搜索',
  'Chats': '聊天',
  'Projects': '项目',
  'Pinned': '已固定',
  'Chats first': '聊天优先',
  'Sort by': '排序',
  'Created': '创建时间',
  'Updated': '更新时间',
  'New chat': '新聊天',
  'No chats': '没有聊天',
  'Skills Hub': '技能中心',
  'Expand accounts': '展开账户',
  'Collapse accounts': '折叠账户',
  'Accounts': '账户',
  'Reloading…': '重新加载中…',
  'Reload': '重新加载',
  'Run `codex login`, then click reload.': '先运行 `codex login`，然后点击重新加载。',
  'Account': '账户',
  'Workspace': '工作区',
  'Require ⌘ + enter to send': '需要 ⌘ + Enter 才发送',
  'When busy, send as': '忙碌时发送方式',
  'Steer': '引导',
  'Queue': '排队',
  'Appearance': '外观',
  'System': '跟随系统',
  'Dark': '深色',
  'Light': '浅色',
  'Chat width': '聊天宽度',
  'Click to toggle dictation': '点击切换语音输入',
  'Auto send dictation': '语音输入后自动发送',
  'Provider': '提供方',
  'Choose the API provider for the Codex backend': '选择 Codex 后端使用的 API 提供方',
  'OpenRouter API key': 'OpenRouter API Key',
  'Get API key': '获取 API Key',
  'Remove custom key, use community keys': '移除自定义 key，改用社区 key',
  'Set': '设置',
  'Save': '保存',
  'API format': 'API 格式',
  'OpenRouter API format': 'OpenRouter API 格式',
  'Responses': 'Responses',
  'Completions': 'Completions',
  'OpenCode Zen API key': 'OpenCode Zen API Key',
  'Custom endpoint URL': '自定义端点 URL',
  'API key': 'API Key',
  'Custom endpoint API format': '自定义端点 API 格式',
  'UI language': '界面语言',
  'Choose the interface language for the app.': '选择应用界面语言。',
  'Dictation language': '听写语言',
  'Auto-detect': '自动检测',
  'Search language...': '搜索语言...',
  'Telegram': 'Telegram',
  'Bot token': 'Bot Token',
  'Allowed Telegram user IDs': '允许的 Telegram 用户 ID',
  'Put one Telegram user ID per line or separate them with commas. Use `*` to allow all Telegram users. Unauthorized users will see their own ID in the rejection message so they can copy it here.': '每行填写一个 Telegram 用户 ID，或用逗号分隔。使用 `*` 可允许所有 Telegram 用户。未授权用户会在拒绝消息中看到自己的 ID，方便复制到这里。',
  'Saving…': '保存中…',
  'Save Telegram config': '保存 Telegram 配置',
  'Context': '上下文',
  'Worktree name and version': '工作树名称和版本',
  'Settings': '设置',
  'General settings': '常规',
  'Models & providers': '模型与提供商',
  'Integrations': '集成',
  'Usage & about': '用量与关于',
  'Thinking process': '思考过程',
  'Working…': '执行中…',
  'Processed': '已处理',
  '{n} tools': '{n} 个工具',
  '{n} thoughts': '{n} 条思考',
  '{n} commands': '{n} 个命令',
  'Question navigation': '问题导航',
  'Jump to question {n}': '跳转到问题 {n}',
  'Read {n} files': '已读 {n} 个文件',
  'Search {n} files': '搜索 {n} 个文件',
  '{n} read calls': '{n} 次只读调用',
  'Modified {n} files': '已修改 {n} 个文件',
  'Delegated {n} tasks': '已委派 {n} 个任务',
  'Explored {n} items': '已探索 {n} 项',
  'Stopped: message not submitted, restored to input.': '已停止：消息未提交，已回填到输入框。',
  'Stopped: message not submitted.': '已停止：消息未提交。',
  'Load earlier ({n} turns)': '展开前 {n} 轮对话',
  'Load earlier messages': '加载更早的消息',
  'Steps': '步骤',
  'Implement plan': '执行计划',
  'Plan executed': '计划已执行',
  'Implementing…': '执行中…',
  'Toggle terminal': '切换终端',
  'Open terminal': '打开终端',
  'Terminal command': '终端命令',
  'No commands': '没有命令',
  'Search branches...': '搜索分支...',
  "Let's build": '开始构建',
  'Choose folder': '选择文件夹',
  'Quick search project': '快速搜索项目',
  'Selected folder': '已选文件夹',
  'Select folder': '选择文件夹',
  'Create Project': '创建项目',
  'Create or clone': '创建或克隆',
  'Create or clone project': '创建或克隆项目',
  'Project source': '项目来源',
  'New project': '新项目',
  'Destination folder': '目标文件夹',
  'New project name': '新项目名称',
  'GitHub repository URL': 'GitHub 仓库 URL',
  'Create project': '创建项目',
  'Creating…': '创建中…',
  'Clone repository': '克隆仓库',
  'Clone from GitHub': '从 GitHub 克隆',
  'Cloning…': '克隆中…',
  'Current folder': '当前文件夹',
  'Unavailable': '不可用',
  'Opening…': '打开中…',
  'Open': '打开',
  'Show hidden folders': '显示隐藏文件夹',
  'New folder': '新建文件夹',
  'Folder name': '文件夹名称',
  'Filter folders...': '筛选文件夹...',
  'Retry': '重试',
  'Loading folders…': '加载文件夹中…',
  'No folders match this filter.': '没有匹配此筛选条件的文件夹。',
  'No subfolders found here.': '这里没有子文件夹。',
  'Base branch': '基础分支',
  'Select branch': '选择分支',
  'Loading branches…': '加载分支中…',
  'No Git branches found for this folder.': '此文件夹未找到 Git 分支。',
  'Local project': '本地项目',
  'New worktree': '新工作树',
  'Service worker registration failed.': 'Service Worker 注册失败。',
  'No matching files': '没有匹配的文件',
  'Add photos & files': '添加图片和文件',
  'Add folder': '添加文件夹',
  'Take photo': '拍照',
  'In-progress send': '执行中发送',
  'Fast mode': '快速模式',
  'Plan mode': '规划模式',
  'Agent proposes a plan before acting': '代理在执行前先提出计划',
  'Model': '模型',
  'Search models...': '搜索模型...',
  'Skills': '技能',
  'Search skills...': '搜索技能...',
  'Search skills and prompts...': '搜索技能和提示词...',
  'Thinking': '思考强度',
  'Saving thread before stop is available': '线程保存后才能停止',
  'Stop': '停止',
  'This thread is running in the Codex TUI': '该线程正在 Codex TUI 中运行',
  'Queue message': '加入队列',
  'Send message': '发送消息',
  'Send': '发送',
  'Drop images or files': '拖放图片或文件',
  'Selected image': '已选图片',
  'Loading messages...': '加载消息中...',
  'Plan': '计划',
  'Updating': '更新中',
  'Step': '步骤',
  'Edit this message': '编辑此消息',
  'Edit message': '编辑消息',
  'Rollback this message': '回退此消息',
  'Rollback': '回退',
  'Fork thread from this response': '从此回复分叉线程',
  'Fork': '分叉',
  'Response copied': '回复已复制',
  'Copy response': '复制回复',
  'Jump to latest': '跳转到最新',
  'Jump to latest output': '跳转到最新输出',
  'Close image preview': '关闭图片预览',
  'Expanded message image': '放大消息图片',
  'Changed files': '已更改文件',
  'Close diff viewer': '关闭 diff 查看器',
  'No diff available': '没有可用 diff',
  'This summary was restored from the final answer text, but the thread history does not include patch diff content for this file.': '此摘要是从最终回答文本恢复的，但线程历史中不包含该文件的补丁 diff 内容。',
  'Review': '审查',
  'Commit': '提交',
  'Close review pane': '关闭审查面板',
  'Compare': '比较',
  'Branch': '分支',
  'Changes': '更改',
  'Loading review state': '加载审查状态中',
  'This folder is not a Git repository': '此文件夹不是 Git 仓库',
  'Initialize Git to review local changes and run Codex review.': '初始化 Git 后即可审查本地更改并运行 Codex review。',
  'Initializing…': '初始化中…',
  'Initialize Git': '初始化 Git',
  'Base branch unavailable': '基础分支不可用',
  'Could not resolve `origin/HEAD`, `main`, or `master` for this repository.': '无法为此仓库解析 `origin/HEAD`、`main` 或 `master`。',
  'No changes in this scope': '此范围内没有更改',
  'No file changes in this commit.': '此提交中没有文件更改。',
  'Your current workspace is clean.': '当前工作区很干净。',
  'No merge diff found against the base branch.': '未找到相对基础分支的合并 diff。',
  'No unified diff available.': '没有可用的统一 diff。',
  'Summary': '摘要',
  'Added': '新增',
  'Deleted': '删除',
  'Renamed': '重命名',
  'Modified': '修改',
  'Repository review': '仓库审查',
  'Staged changes': '已暂存更改',
  'Workspace changes': '工作区更改',
  'Unstage all': '全部取消暂存',
  'Stage all': '全部暂存',
  'Revert all': '全部还原',
  'Unstage file': '取消暂存文件',
  'Stage file': '暂存文件',
  'Revert file': '还原文件',
  'Unstage hunk': '取消暂存代码块',
  'Stage hunk': '暂存代码块',
  'Revert hunk': '还原代码块',
  'Failed to load review snapshot': '加载审查快照失败',
  'Failed to apply review action': '应用审查操作失败',
  'Failed to initialize Git': '初始化 Git 失败',
  'Reviewing current changes': '正在审查当前更改',
  'Failed to start review': '启动审查失败',
  'Review in progress': '审查进行中',
  'Failed to load review result': '加载审查结果失败',
  'pin': '固定',
  'Worktree thread': '工作树线程',
  'Threads': '线程',
  'Organize threads': '整理线程',
  'Organize': '整理',
  'By project': '按项目',
  'Chronological list': '按时间顺序',
  'No matching threads': '没有匹配的线程',
  'Loading threads...': '加载线程中...',
  'Edit name': '编辑名称',
  'Remove': '移除',
  'Project name': '项目名称',
  'No threads': '没有线程',
  'Thread title': '线程标题',
  'Rename thread': '重命名线程',
  'Make it short and recognizable.': '尽量简短且易识别。',
  'Add title...': '输入标题...',
  'Cancel': '取消',
  'Delete thread': '删除线程',
  'Thread automation': '线程自动化',
  'This creates a heartbeat automation attached to the selected thread.': '这会创建一个附加到所选线程的心跳自动化。',
  'Name': '名称',
  'Automation name': '自动化名称',
  'Prompt': '提示词',
  'Search prompt...': '搜索提示词...',
  'Describe what the automation should do': '描述自动化需要执行的内容',
  'Schedule (RRULE)': '计划（RRULE）',
  'Status': '状态',
  'Active': '启用',
  'Paused': '暂停',
  'Expand sidebar': '展开侧边栏',
  'Collapse sidebar': '折叠侧边栏',
  'Start new thread': '新建线程',
  'No skills found': '未找到技能',
  'No results': '没有结果',
  'Approval choices': '审批选项',
  'No, and tell Codex what to do differently': '不允许，并告诉 Codex 应如何调整',
  'Skip': '跳过',
  'Yes': '是',
  'Yes for Session': '本次会话内允许',
  'pending': '条待处理',
  'Do you want to run this command?': '是否运行此命令？',
  'Do you want to make these changes?': '是否进行这些更改？',
  'Do you want to grant these permissions?': '是否授予这些权限？',
  'An MCP server needs your input before Codex can continue.': 'MCP 服务器需要你的输入，Codex 才能继续。',
  'Codex needs your answer before it can continue.': 'Codex 需要你的回答才能继续。',
  'Codex is waiting for a response before it can continue.': 'Codex 正在等待你的回复，然后才能继续。',
  'Server': '服务器',
  'Open authorization link': '打开授权链接',
  'Value': '值',
  'Choice': '选项',
  'Select true or false': '选择 true 或 false',
  'True': 'True',
  'False': 'False',
  'Select an option': '选择一个选项',
  'Decline': '拒绝',
  'Continue': '继续',
  'Other answer': '其他答案',
  'Fail Tool Call': '使工具调用失败',
  'Success (Empty)': '成功（空结果）',
  'Return Empty Result': '返回空结果',
  'New terminal': '新终端',
  'Hide terminal': '隐藏终端',
  'Close': '关闭',
  'Edit queued message': '编辑排队消息',
  'Send now without interrupting work': '立即发送且不中断当前工作',
  'Delete queued message': '删除排队消息',
  'AppServer API': 'AppServer API',
  'Loading method catalog...': '加载方法目录中...',
  'Disabled': '已禁用',
  'Installed': '已安装',
  'Browse files': '浏览文件',
  'Loading skill contents...': '加载技能内容中...',
  'View on GitHub': '在 GitHub 查看',
  'Show all': '显示全部',
  'Hide all': '隐藏全部',
  'No types yet': '还没有类型',
  'Manage installed skills on this machine': '管理此机器上已安装的技能',
  'Skills Sync (GitHub)': '技能同步（GitHub）',
  'Connected': '已连接',
  'Logged in as': '已登录为',
  'Not connected': '未连接',
  'Startup': '启动',
  'Action': '动作',
  'Skill': '技能',
  'Manual sync': '手动同步',
  'GitHub device login': 'GitHub 设备登录',
  'and enter code:': '并输入代码：',
  'Login with GitHub': '使用 GitHub 登录',
  'Device Login': '设备登录',
  'Logout GitHub': '退出 GitHub',
  'Syncing...': '同步中...',
  'Startup Sync': '启动同步',
  'Pulling...': '拉取中...',
  'Pull': '拉取',
  'Pushing...': '推送中...',
  'Push': '推送',
  'Installed ({count})': '已安装（{count}）',
  'Find skills': '查找技能',
  'Search the Skills registry with npx skills find.': '使用 npx skills find 搜索 Skills 注册表。',
  'Searching...': '搜索中...',
  'Search results ({count})': '搜索结果（{count}）',
  'No matching skills found.': '未找到匹配的技能。',
  'No installed skills found.': '未找到已安装的技能。',
  'Continue in': '运行方式',
  'Search daily': '搜索（日）',
  'Search weekly': '搜索（周）',
  'Search monthly': '搜索（月）',
  'Trending daily': '热门（日）',
  'Trending weekly': '热门（周）',
  'Trending monthly': '热门（月）',
  'Newest': '最新',
  'A-Z': 'A-Z',
  'Loading skills...': '加载技能中...',
  'Choose a thread': '选择一个线程',
  'New worktree branch will start from {branch}.': '新工作树分支将从 {branch} 开始。',
  'Local project uses the selected folder directly. New worktree creates an isolated Git worktree before the first prompt.': '本地项目会直接使用所选文件夹。新工作树会在第一次提问前创建一个隔离的 Git worktree。',
  'Not configured': '未配置',
  'Online': '在线',
  'Configured (offline)': '已配置（离线）',
  'allow all users': '允许所有用户',
  'allowed user(s)': '个允许用户',
  'chat(s)': '个聊天',
  'thread(s)': '个线程',
  'error': '错误',
  'unknown': '未知',
  'Switching…': '切换中…',
  'Switch': '切换',
  'Removing…': '移除中…',
  'Click again to remove': '再次点击以移除',
  '402 Payment Required': '402 需要付费',
  'weekly remaining': '周剩余额度',
  'Unlimited credits': '无限额度',
  'credits': '额度',
  'Loading quota…': '加载额度中…',
  'Quota unavailable': '额度不可用',
  'Fetching account details…': '获取账户详情中…',
  'Unavailable account': '不可用账户',
  'Waiting for Codex thread/tokenUsage/updated events for this thread.': '等待此线程的 Codex tokenUsage 更新事件。',
  'Current context usage': '当前上下文使用量',
  'Cumulative thread usage': '累计线程使用量',
  'Model context window': '模型上下文窗口',
  'Remaining context': '剩余上下文',
  'tokens': 'tokens',
  'Model context window is unavailable in the latest usage event.': '最新使用事件中未提供模型上下文窗口。',
  'Awaiting data': '等待数据中',
  'left': '剩余',
  'used': '已用',
  'Updates after the next token usage event': '下次 token 使用事件后更新',
  'Window size unavailable': '窗口大小不可用',
  'Telegram bot token is required.': '需要填写 Telegram Bot Token。',
  'At least one allowed Telegram user ID or * is required.': '至少需要一个允许的 Telegram 用户 ID 或 `*`。',
  'Telegram bot configured. Only allowlisted Telegram users can use the bridge.': 'Telegram 机器人已配置。只有白名单中的 Telegram 用户可以使用桥接。',
  'Failed to connect Telegram bot': '连接 Telegram 机器人失败',
  'Failed to load accounts': '加载账户失败',
  'Failed to refresh accounts': '刷新账户失败',
  'Login': '登录',
  'Starting login…': '正在启动登录…',
  'Open login URL': '打开登录链接',
  'Paste localhost callback URL': '粘贴 localhost 回调 URL',
  'Complete Codex login': '完成 Codex 登录',
  'Finish login in the browser, then paste the localhost callback URL here.': '在浏览器中完成登录，然后在这里粘贴 localhost 回调 URL。',
  'Complete': '完成',
  'Completing…': '正在完成…',
  'Failed to start Codex login': '启动 Codex 登录失败',
  'Failed to complete Codex login': '完成 Codex 登录失败',
  'Click Login, or run `codex login`, then click reload.': '点击登录，或运行 `codex login`，然后点击重新加载。',
  'Finish the current turn and pending requests before switching accounts.': '请先完成当前轮次并处理待处理请求后再切换账户。',
  'Failed to switch account': '切换账户失败',
  'Finish the current turn and pending requests before removing the active account.': '请先完成当前轮次并处理待处理请求后再移除当前活动账户。',
  'Failed to remove account': '移除账户失败',
  'enabled': '已启用',
  'disabled': '已禁用',
  'Saving speed setting...': '保存速度设置中...',
  'About 1.5x faster, with credits used at 2x': '速度约提升 1.5 倍，额度消耗为 2 倍',
  'Default speed with normal credit usage': '默认速度，按正常额度消耗',
  'Stop dictation': '停止听写',
  'Click to dictate': '点击开始听写',
  'Hold to dictate': '按住听写',
  'failed': '失败',
  'attaching': '正在附加',
  'Attaching': '正在附加',
  'Attaching file...': '正在附加文件...',
  'files...': '个文件...',
  'attached': '已附加',
  'Could not attach file.': '无法附加文件。',
  'Could not attach': '无法附加',
  'files.': '个文件。',
  'Select a thread to send a message': '选择一个线程后才能发送消息',
  'Loading models for plan mode...': '正在为规划模式加载模型...',
  'Ask Codex anything, @ to add files, / for commands': '向 Codex 提问，@ 添加文件，/ 执行命令',
  'Hide': '隐藏',
  'Terminal': '终端',
  'Terminal input failed': '终端输入失败',
  'Terminal attach failed': '终端附加失败',
  'Creating worktree': '创建工作树',
  'Creating a worktree and running setup.': '正在创建工作树并执行初始化。',
  'Worktree setup failed': '工作树初始化失败',
  'Unable to create worktree. Try again or switch to Local project.': '无法创建工作树。请重试，或切换到本地项目。',
  'Edit': '编辑',
  'Edit automation': '编辑自动化',
  'image': '图片',
  'images': '图片',
  'file': '文件',
  'files': '文件',
  'skill': '技能',
  'skills': '技能',
  '(empty queued message)': '（空的排队消息）',
  'Files': '文件',
  'Unstaged': '未暂存',
  'Staged': '已暂存',
  'Refresh': '刷新',
  'Against': '对比',
  'selected': '已选',
  'Reject Request': '拒绝请求',
  'Uninstalling...': '卸载中...',
  'Uninstall': '卸载',
  'Installing...': '安装中...',
  'Install': '安装',
  'Disable': '禁用',
  'Enable': '启用',
  'When enabled, press Enter to send. When disabled, use Command+Enter to send.': '启用时按 Enter 发送；禁用时使用 Command+Enter 发送。',
  'If a turn is still running, choose whether a new prompt should steer the current turn or be queued.': '如果当前轮次仍在运行，选择新提示是引导当前轮次还是加入队列。',
  'Switch between system theme, light mode, and dark mode.': '在跟随系统、浅色和深色主题之间切换。',
  'Choose how wide the conversation column and composer can grow on desktop screens.': '选择桌面端会话列和输入框的最大宽度。',
  'Use click-to-start and click-to-stop dictation instead of hold-to-talk.': '使用点击开始/停止听写，而不是按住说话。',
  'Automatically send transcribed dictation when recording stops.': '录音停止后自动发送转写结果。',
  'Show or hide GitHub trending project cards on the new thread screen.': '显示或隐藏新线程页面上的 GitHub 热门项目卡片。',
  'Choose transcription language or keep auto-detect.': '选择转写语言，或保持自动检测。',
  'Standard': '标准',
  'Wide': '宽',
  'Extra wide': '超宽',
  'Hooks': 'Hooks',
  'Reload lifecycle hooks': '重新加载生命周期 Hooks',
  'Hooks are not supported by this Codex version.': '当前 Codex 版本不支持 Hooks。',
  'Loading hooks…': '加载 Hooks 中…',
  'No hooks registered.': '未注册任何 Hooks。',
  'Global': '全局',
  'Enabled': '已启用',
  'Compacting thread context…': '正在压缩上下文…',
  'Context compacted': '上下文已压缩',
  'Approval policy': '审批策略',
  'Choose when Codex asks for your permission before running commands or changing files.': '选择 Codex 在执行命令或修改文件前何时征求你的许可。',
  'Only untrusted commands': '仅不受信任的命令',
  'After a command fails': '命令失败后',
  'When Codex requests it': '请求时',
  'Never': '从不',
  'Unless trusted': '除非信任',
  'Default': '默认',
  'Execution plans': '执行计划',
  'Not supported by this Codex version': '当前 Codex 版本不支持',
  'Remote control': '远程控制',
  'Enable or disable remote control': '启用或禁用远程控制',
  'Remote control is not supported by this Codex version.': '当前 Codex 版本不支持远程控制。',
  'Pair a new device': '配对新设备',
  'Generate code': '生成配对码',
  'Paired devices': '已配对设备',
  'No paired devices.': '暂无已配对设备。',
  'Revoke': '撤销',
  'Starting…': '启动中…',
  'Add panel': '添加面板',
  'Approval policy saved': '审批策略已保存',
  'Automations': '自动化',
  'Bearer token (optional)': 'Bearer Token（可选）',
  'Close panel': '关闭面板',
  'Close side panel': '关闭侧边面板',
  'Codex': 'Codex',
  'Compact': '压缩',
  'Compacting…': '正在压缩…',
  'Compacts context before send': '发送前压缩上下文',
  'Auto-compact before send': '发送前自动压缩',
  'Compacting context — the message will send after compaction': '正在压缩上下文——消息将在压缩完成后发送',
  'Auto-compact at or below remaining context percentage. 0 disables auto-compaction and falls back to server-side compaction.': '当剩余上下文占比等于或低于该百分比时，发送前先自动压缩上下文。0 表示关闭，退回服务端自动压缩。',
  'Custom endpoint': '自定义端点',
  'Off': '关闭',
  'Dismiss': '忽略',
  'Download': '下载',
  'Drag to reorder queued message': '拖动可重新排列排队消息',
  'Exit full screen composer': '退出全屏输入框',
  'Expand composer': '展开输入框',
  'Explore Plugins & Apps': '探索插件与应用',
  'Export Project': '导出项目',
  'Exporting': '正在导出',
  'Failed to share project. Use Download instead.': '项目分享失败，请改用下载。',
  'Files panel': '文件面板',
  'Filter files...': '筛选文件...',
  'Git': 'Git',
  'Git panel': 'Git 面板',
  'Hook Codex up to Gmail, Calendar, GitHub, Slack, Browser Use, and more so it can actually help with real work right away.': '将 Codex 接入 Gmail、日历、GitHub、Slack、Browser Use 等应用，让它可以立即帮你处理实际工作。',
  'Import Project': '导入项目',
  'Importing…': '正在导入…',
  'Issue detected': '发现问题',
  'Loading files...': '加载文件中...',
  'Loading…': '加载中…',
  'New in Codex': 'Codex 新功能',
  'No files in workspace.': '工作区中没有文件。',
  'No searchable directory for this thread': '此线程没有可搜索的目录',
  'Open side panel': '打开侧边面板',
  'OpenCode Zen': 'OpenCode Zen',
  'OpenRouter': 'OpenRouter',
  'Plugin': '插件',
  'Plugins are here': '插件来了',
  'Plugins, apps, MCPs': '插件、应用、MCP',
  'Preparing project ZIP...': '正在准备项目 ZIP...',
  'Preparing...': '正在准备...',
  'Ready': '就绪',
  'Repo': '仓库',
  'Scheduled work': '定时任务',
  'Search': '搜索',
  'Search options...': '搜索选项...',
  'Send feedback': '发送反馈',
  'Share': '分享',
  'Skills directory': '技能目录',
  'Terminal panel': '终端面板',
  'This browser blocked sharing the ZIP. Use Download instead.': '浏览器阻止了分享 ZIP，请改用下载。',
  'User': '用户',
  'sk-or-v1-... (optional, uses free keys if empty)': 'sk-or-v1-...（可选，留空则使用免费 key）',
  'File preview': '文件预览',
  'Loading file…': '正在加载文件…',
  'Failed to preview file': '文件预览失败',
  'This file type cannot be previewed.': '此文件类型无法预览。',
  'Open in browser': '在浏览器中打开',
  'File is large; showing the first part.': '文件较大，仅显示开头部分。',
  'Confirm delete': '确认删除',
  'Confirm': '确认',
  'Authenticated': '已认证',
  'Failed': '失败',
  'Logged in': '已登录',
  'Unknown': '未知',
  'No auth': '无需认证',
  'No auth required': '无需认证',
  'Connection required': '需要连接',
  'Composio workspace': 'Composio 工作区',
  'Apps needing auth': '需要认证的应用',
  'Plugin shares': '插件分享',
  'Connector': '连接器',
  'connected': '已连接',
  'account': '个账户',
  'accounts': '个账户',
  'Manage': '管理',
  'Reconnect': '重新连接',
  'Connect': '连接',
  'App': '应用',
  'Plugins': '插件',
  'Apps': '应用',
  'Composio CLI shares the login and connections from this machine.': 'Composio CLI 共享本机的登录状态与连接。',
  'Bearer token': 'Bearer Token',
  'Login required': '需要登录',
  'Auth unsupported': '不支持认证',
  'Status unknown': '状态未知',
  'OpenAI catalog': 'OpenAI 目录',
  'Ecosystem directory': '生态系统目录',
  'Expired': '已过期',
  'Pending': '待处理',
  'Plugins make Codex work your way.': '插件让 Codex 按你的方式工作。',
  'Connect Codex to external apps and services.': '将 Codex 连接到外部应用与服务。',
  'Browse Composio connectors, auth state, and ready-to-try integrations.': '浏览 Composio 连接器、认证状态与可直接尝试的集成。',
  'MCPs first, then installed skills and GitHub sync state.': '先看 MCP，再是已安装技能与 GitHub 同步状态。',
  'Close plugin detail': '关闭插件详情',
  'Close plugin shares': '关闭插件分享',
  'Close Composio detail': '关闭 Composio 详情',
  'Add another automation': '再添加一个自动化',
  'New thread': '新建线程',
  'methods': '个方法',
  'Schedule': '计划',
  'Daily': '每天',
  'days': '天',
  'Interval': '间隔',
  'Run every day at': '每天运行时间',
  'Run every': '每隔',
  'Unit': '单位',
  'Running…': '运行中…',
  'Run now': '立即运行',
  'Archive and remove': '归档并移除',
  'Delete': '删除',
  'This will archive the thread "{title}" and remove the attached heartbeat automations.': '这将归档线程「{title}」并移除其关联的心跳自动化。',
  'This will archive the thread "{title}". You can find it later in archived threads.': '这将归档线程「{title}」。你之后可以在已归档线程中找到它。',
  'Recycle bin': '回收站',
  'Threads you removed are kept here so you can restore them.': '被移除的线程会保存在这里，你可以随时还原。',
  'Recycle bin is empty.': '回收站是空的。',
  'Restore': '还原',
  'Restoring…': '还原中…',
  'Delete permanently': '永久删除',
  'Delete thread?': '删除线程？',
  'Archive chat and remove automations?': '归档聊天并移除自动化？',
  // ---- 动态文案（script 内拼接） ----
  'active': '个进行中',
  'added': '已新增',
  'Add automation': '添加自动化',
  'Add automation…': '添加自动化…',
  'ago': '前',
  'Answer the required field': '请填写必填字段',
  'app': '应用',
  'automations': '个自动化',
  'cached': '缓存',
  'changed': '已更改',
  'Checkout': '检出',
  'Checking out...': '检出中…',
  'command:': '命令：',
  'Context window': '上下文窗口',
  'Copy path': '复制路径',
  'Credits': '额度',
  'cwd:': '工作目录：',
  'day(s)': '天',
  'deleted': '已删除',
  'Detached': '已分离',
  'edited': '已编辑',
  'Edited': '已编辑',
  'Every': '每',
  'exitCode:': '退出码：',
  'Failed to connect {name}': '连接 {name} 失败',
  'Failed to start login for {name}': '为 {name} 启动登录失败',
  'file changed': '个文件已更改',
  'files changed': '个文件已更改',
  'hour(s)': '小时',
  'hours': '小时',
  'Image': '图片',
  'input': '输入',
  'Last turn': '上一轮',
  'Manage automations…': '管理自动化…',
  'minute(s)': '分钟',
  'minutes': '分钟',
  'moved': '已移动',
  'Network access': '网络访问',
  'Next': '下次',
  'Next run': '下次运行',
  'Not scheduled': '未计划',
  'RRULE': '规则',
  'No login URL returned for {name}': '未返回 {name} 的登录链接',
  'Opened {name} authorization': '已打开 {name} 授权',
  'output': '输出',
  'plugin': '插件',
  'plugin installed': '插件已安装',
  'plugin uninstalled': '插件已卸载',
  'Preferred': '首选',
  'Primary window': '主窗口',
  'Project automation': '项目自动化',
  'Read': '读取',
  'reasoning': '推理',
  'Removing...': '移除中…',
  'resets in': '重置于',
  'Resets in': '重置于',
  'runs every': '每',
  'Secondary window': '次窗口',
  'Session total': '会话总计',
  'Share this plugin': '共享此插件',
  'Sharing...': '共享中…',
  'Show': '显示',
  'skill installed': '技能已安装',
  'skill uninstalled': '技能已卸载',
  'start new thread': '新建线程',
  'status:': '状态：',
  'total': '总计',
  'Weekly refresh': '每周刷新',
  'Write': '写入',
  // ---- 动态文案（模板内补充） ----
  'Current branch': '当前分支',
  'Credits available': '额度可用',
  'Custom schedule': '自定义计划',
  'Detached HEAD': '已分离 HEAD',
  'Every minute': '每分钟',
  'Hourly': '每小时',
  'In context': '上下文内',
  'Loading branch...': '加载分支中...',
  'Rate limits': '速率限制',
  'Resetting now': '正在重置',
  'unlimited': '无限',
  'Weekly': '每周',
  'Window': '窗口',
  // ---- 第四轮：右键菜单/编辑弹窗/自动化/技能/Git 面板 ----
  'Automation details': '自动化详情',
  'Automation run queued.': '自动化运行已排队。',
  'Automation saved.': '自动化已保存。',
  'Awaiting approval': '等待审批',
  'Awaiting response': '等待响应',
  'Branches': '分支',
  'command': '个命令',
  'commands': '个命令',
  'Command approval required': '需要命令审批',
  'Commits': '提交',
  'Completed': '已完成',
  'Copied commit ref': '已复制提交引用',
  'Copy': '复制',
  'Copy chat': '复制聊天',
  'Create a new automation': '创建新自动化',
  'Create chat fork': '创建聊天分叉',
  'current': '当前',
  'Declined': '已拒绝',
  'Done': '完成',
  'Rollback this turn?': '回退到该轮？',
  'Exit': '退出',
  'Failed to delete project automation': '删除项目自动化失败',
  'Failed to install skill': '安装技能失败',
  'Failed to load automations': '加载自动化失败',
  'Failed to load skills': '加载技能失败',
  'Failed to remove automation': '移除自动化失败',
  'Failed to run automation': '运行自动化失败',
  'Failed to save automation': '保存自动化失败',
  'Failed to search skills': '搜索技能失败',
  'Failed to uninstall skill': '卸载技能失败',
  'Failed to update file changes.': '更新文件变更失败。',
  'Failed to update skill': '更新技能失败',
  'File change approval required': '需要文件变更审批',
  'Heartbeat': '心跳',
  'Input required': '需要输入',
  'Install completed but no local skill path was returned': '安装完成，但未返回本地技能路径',
  'Install completed but the local skill was not found after refresh': '安装完成，但刷新后未找到本地技能',
  'Install failed': '安装失败',
  'Interrupted': '已中断',
  'latest:': '最新：',
  'Loading automations...': '加载自动化中...',
  'Loading commits...': '加载提交中...',
  'MCP server input required': '需要 MCP 服务器输入',
  'Modified files': '修改的文件',
  'New automation': '新自动化',
  'No automations yet': '还没有自动化',
  'No branches found.': '未找到分支。',
  'No commits found.': '未找到提交。',
  'No file changes.': '无文件更改。',
  'No file changes to redo.': '没有可重做的文件变更。',
  'No file changes to undo.': '没有可撤销的文件变更。',
  'No messages in this thread yet.': '此线程还没有消息。',
  'now': '刚刚',
  'Open this chat before copying': '请先打开此聊天再复制',
  'Pin thread': '固定线程',
  'Unpin thread': '取消固定线程',
  'paused': '个已暂停',
  'Permissions approval required': '需要权限审批',
  'Project': '项目',
  'Project automation requires a resolved absolute project path.': '项目自动化需要已解析的绝对项目路径。',
  'Redo': '重做',
  'Redo file changes?': '重做文件变更？',
  'Redo the file changes from this turn? This reapplies the edits to the working tree.': '重做本轮的文件变更？这会重新将修改应用到工作树。',
  'Redoing': '正在重做',
  'Refreshing...': '刷新中...',
  'Rejected from codex-web-local UI.': '已在 codex-web-local 界面中拒绝。',
  'Rename project': '重命名项目',
  'Reset': '重置',
  'Reset-history refs': '重置历史引用',
  'remote': '远程',
  'Review Worktree Changes': '审查工作树更改',
  'Review Worktree Changes (Open)': '审查工作树更改（打开）',
  'Running': '运行中',
  'Search commits...': '搜索提交...',
  'Search skills': '搜索技能',
  'Select a branch.': '请选择一个分支。',
  'Select a chat target for this automation': '为此自动化选择一个聊天目标',
  'Select a project target for this automation': '为此自动化选择一个项目目标',
  'Stopped': '已停止',
  'Command blocked by a permission or sandbox restriction; no approval prompt was shown. Check the approval policy or trusted directories if you expected one.': '命令因权限或沙箱限制被拦截，未弹出审批提示。如预期应出现审批，请检查审批策略或受信任目录。',
  'Target': '目标',
  'This creates a heartbeat automation attached to the selected chat.': '这会在所选聊天上创建一个心跳自动化。',
  'This creates a project automation attached to the selected project folder.': '这会在所选项目文件夹上创建一个项目自动化。',
  'This creates heartbeat automations attached to the selected thread.': '这会在所选线程上创建心跳自动化。',
  'This creates project automations attached to the selected project folder.': '这会在所选项目文件夹上创建项目自动化。',
  'This rolls the thread back to this turn so you can edit the message. Later replies will be removed.': '将线程回退到本轮，以便你编辑消息。之后的回复将被移除。',
  'Tool call rejected from codex-web-local UI.': '工具调用已在 codex-web-local 界面中拒绝。',
  'Tool call waiting for response': '工具调用等待响应',
  'Tracked changes must be committed, stashed, or discarded before switching or resetting. Untracked files are allowed unless Git would overwrite them.': '切换或重置前，必须提交、暂存或丢弃已跟踪的更改。除非 Git 会覆盖，否则允许存在未跟踪的文件。',
  'Undo': '撤销',
  'Undo file changes?': '撤销文件变更？',
  'Undo the file changes from this turn? This modifies the working tree and Codex cannot revert it automatically.': '撤销本轮的文件变更？这会修改工作树，Codex 无法自动还原。',
  'Undo the changes to {file}? This modifies the working tree and Codex cannot revert it automatically.': '撤销对 {file} 的变更？这会修改工作树，Codex 无法自动还原。',
  'Redo the changes to {file}? This reapplies the edits to the working tree.': '重做对 {file} 的变更？这会重新应用对工作树的编辑。',
  'Undoing': '正在撤销',
  'Uninstall failed': '卸载失败',
  'Use a thread or project menu to add an automation.': '请通过线程或项目菜单添加自动化。',
}

const LANGUAGE_LABELS: Record<UiLanguage, string> = {
  en: 'English',
  'zh-CN': '简体中文',
}

function readStoredLanguage(): UiLanguage {
  if (typeof window === 'undefined') return 'en'
  const raw = window.localStorage.getItem(UI_LANGUAGE_STORAGE_KEY)?.trim()
  return raw === 'zh-CN' ? 'zh-CN' : 'en'
}

const currentLanguage = ref<UiLanguage>(readStoredLanguage())

function applyDocumentLanguage(language: UiLanguage): void {
  if (typeof document === 'undefined') return
  document.documentElement.lang = language === 'zh-CN' ? 'zh-CN' : 'en'
  document.documentElement.dataset.uiLanguage = language
}

applyDocumentLanguage(currentLanguage.value)

function formatTemplate(template: string, params?: Record<string, string | number>): string {
  if (!params) return template
  return template.replace(/\{(\w+)\}/g, (_match, key: string) => String(params[key] ?? ''))
}

export function setUiLanguage(language: UiLanguage): void {
  currentLanguage.value = language
  applyDocumentLanguage(language)
  if (typeof window !== 'undefined') {
    window.localStorage.setItem(UI_LANGUAGE_STORAGE_KEY, language)
  }
}

export function t(message: string, params?: Record<string, string | number>): string {
  const translated = currentLanguage.value === 'zh-CN' ? (zhCN[message] ?? message) : message
  return formatTemplate(translated, params)
}

export function useUiLanguage() {
  return {
    uiLanguage: currentLanguage,
    uiLanguageOptions: [
      { value: 'en', label: LANGUAGE_LABELS.en },
      { value: 'zh-CN', label: LANGUAGE_LABELS['zh-CN'] },
    ] as Array<{ value: UiLanguage; label: string }>,
    t,
    setUiLanguage,
  }
}
